#!/usr/bin/env python3
"""Generate crt0.asm for the clean-room HLE BIOS image (M0).

Nothing here is copied from the SNK BIOS: only the *structure* the hardware
and the emulator core require (vector-table layout, the swi dispatch shape,
the user-vector chaining) is reproduced. All of it is public contract from
the SDK docs / the TLCS-900 architecture.

Image map (64 KiB, linked at 0xFF0000):
  0xFF0000  f_code       boot + dispatcher + ISRs + stubs
  0xFFFE00  SYSCALL_TBL  32 pointers, swi 1 vector index -> stub
  0xFFFF00  INT_VECTOR   60 hardware vectors (reset/swi/IRQ)
"""

import os

# --- user vector table (RAM, 0x6FB8) : which hardware IRQ index maps to
#     which 4-byte slot. Source: ngpcspec.txt "User Program Interrupt Vectors"
#     (the "MICRO DMA START VECTOR" column IS the hardware index).
UVT = 0x6FB8
USER_SLOT = {
    3: UVT + 0 * 4,    # SWI 3
    4: UVT + 1 * 4,    # SWI 4
    5: UVT + 2 * 4,    # SWI 5
    6: UVT + 3 * 4,    # SWI 6
    10: UVT + 4 * 4,   # RTC alarm      (0x6FC8)
    11: UVT + 5 * 4,   # VBlank         (0x6FCC)
    12: UVT + 6 * 4,   # Z80            (0x6FD0)
    16: UVT + 7 * 4,   # Timer 0        (0x6FD4)
    17: UVT + 8 * 4,   # Timer 1
    18: UVT + 9 * 4,   # Timer 2
    19: UVT + 10 * 4,  # Timer 3
    24: UVT + 11 * 4,  # Serial TX      (0x6FE4)
    25: UVT + 12 * 4,  # Serial RX      (0x6FE8)
    29: UVT + 14 * 4,  # End micro-DMA 0 (0x6FF0)
    30: UVT + 15 * 4,  # End micro-DMA 1
    31: UVT + 16 * 4,  # End micro-DMA 2
    32: UVT + 17 * 4,  # End micro-DMA 3
}

# The two serial vectors do NOT trampoline to a user slot: the COM rings belong to
# the BIOS, and the retail BIOS takes these over too. CROSS-WIRED versus the SDK's
# names -- 0x18 ("INTTX0") receives, 0x19 ("INTRX0") transmits. See machine.hpp.
SERIAL_ISR = {0x18: "_isr_ser_rx", 0x19: "_isr_ser_tx"}

HW_TABLE_SLOTS = 60      # 0xFFFF00 .. 0xFFFFF0, 4 bytes each
SYSCALL_SLOTS = 32       # 0xFFFE00 .., swi 1 dispatch indices 0..0x1A used

FONT_FG = 3              # 2bpp pixel index for a lit pixel (default palette)
FONT_BG = 0


FONT_BIN = os.path.join(os.path.dirname(os.path.abspath(__file__)), "font_2bpp.bin")


def build_font_2bpp():
    """The clean-room 8x8 font, expanded to the K2GE 2bpp CHAR-RAM tile format:
    256 tiles x 16 bytes, each row a big-endian word (pixel 0 in the high bits),
    matching the retail SYSFONTSET layout. Returns 0x1000 bytes to preload at
    0xA000.

    Read from the baked font_2bpp.bin, which is what the shipped bios_hle.bin
    was built from. Pillow is NOT a dependency of this module -- it is optional
    everywhere else in the tree (see core/frame_diff.py) and importing it here
    made gen() unrunnable on a bare CI box. Regenerate the .bin with
    `python gen_crt0.py --regen-font`, which needs Pillow and rasterises its
    public-domain default face."""
    with open(FONT_BIN, "rb") as f:
        font = f.read()
    assert len(font) == 0x1000, f"{FONT_BIN}: {len(font)} bytes, expected 0x1000"
    return font


def rasterise_font_2bpp():
    """Rebuild the font bytes from the written-down glyphs in font_glyphs.py.

    ⛔ IT USED TO CALL PILLOW, AND THAT WAS THE BUG. `ImageFont.load_default()`
    is about eleven pixels tall; drawn into an 8x8 box every glyph lost its
    bottom stroke, so the BIOS handed games an `E` shaped like an `F` and an `L`
    with no foot. It also made the SHIPPED IMAGE depend on which Pillow the
    build machine had installed. The glyphs are a table now: no dependency, and
    the same bytes on every machine.
    """
    # By file path, not by sys.path: this module is imported from the test
    # suite as well as run from its own directory.
    import importlib.util
    here = os.path.dirname(os.path.abspath(__file__))
    spec = importlib.util.spec_from_file_location(
        "font_glyphs", os.path.join(here, "font_glyphs.py")
    )
    font_glyphs = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(font_glyphs)
    glyph_rows = font_glyphs.glyph_rows

    out = bytearray()
    for code in range(256):
        rows = glyph_rows(code) if 0x20 <= code < 0x7F else [" " * 8] * 8
        for row in rows:
            word = 0
            for x in range(8):
                word = (word << 2) & 0xFFFF
                word |= FONT_FG if row[x] == "#" else FONT_BG
            # ⛔ LOW BYTE FIRST. A CHAR-RAM row is a 16-bit word stored
            # little-endian, so the byte at the lower address carries the RIGHT
            # half of the row. Writing the halves the other way round swaps them
            # on screen: every glyph came out as its own two halves exchanged,
            # which reads as a font that is nearly right and completely
            # illegible. Checked against the retail BIOS's own 'P' at tile 0x50:
            #   retail  f0 3f | 0c 30 | 0c 30 | f0 3f | 00 30 ...
            out.append(word & 0xFF)          # pixels 4-7
            out.append((word >> 8) & 0xFF)   # pixels 0-3
    assert len(out) == 0x1000
    return bytes(out)


# The system-call table, BY VECTOR NUMBER FROM SYSTEM.INC -- which is the
# authority. A second doc put FLASHPROTECT on 9; 9 is ALARMSET, so following it
# would have had a game's alarm irreversibly protect a flash block instead.
# tests/test_hle_bios_image.py pins these numbers.
SC_STUB = {
    0x00: "_sc_shutdown",      # SHUTDOWN      -> the console switched off
    0x02: "_sc_rtcget",   # RTCGET            -> copy the clock into XHL3 (Ganbare)
    0x04: "_sc_intlvset", # INTLVSET          -> set INTxx priority (Card Fighters Clash 2)
    0x05: "_sc_sysfontset",    # SYSFONTSET    -> font into CHAR RAM, with its palette
    0x06: "_sc_flashwrite",   # FLASHWRITE    -> program the save into the cartridge
    0x07: "_sc_flashallers",  # FLASHALLERS   -> erase the whole chip
    0x08: "_sc_flashers",     # FLASHERS      -> erase one block, by NUMBER
    0x09: "_sc_alarmset",      # ALARMSET      -> RTC alarm (NOT flash protect)
    0x0B: "_sc_alarmdownset",  # ALARMDOWNSET  -> same registers, power-on alarm
    0x0D: "_sc_flashprotect",  # FLASHPROTECT  -> make blocks read-only (irreversible)
    0x0E: "_sc_gemodeset",     # GEMODESET     -> K1GE / K2GE display mode
    0x10: "_sc_cominit",       # COMINIT
    0x11: "_sc_comsendstart",  # COMSENDSTART
    0x12: "_sc_comrecvstart",  # COMRECIVESTART
    0x13: "_sc_comcreatedata", # COMCREATEDATA    -> queue one byte
    0x14: "_sc_comgetdata",    # COMGETDATA       -> pop one byte (or 'empty')
    0x15: "_sc_comonrts",      # COMONRTS         -> ready to receive
    0x16: "_sc_comoffrts",     # COMOFFRTS        -> hold the peer off
    0x17: "_sc_comsendstatus", # COMSENDSTATUS    -> bytes still queued
    0x18: "_sc_comrecvstatus", # COMRECIVESTATUS  -> bytes waiting
    0x19: "_sc_combufsend",    # COMCREATEBUFDATA -> queue a block
    0x1A: "_sc_combufget",     # COMGETBUFDATA    -> pop a block
}


def card_block_offsets(capacity):
    """The card's blocks, in order, as offsets -- the SDK's own numbering. 64 KiB all
    the way up, then the last 64 KiB split 32 / 8 / 8 / 16. The block NUMBER a game
    passes indexes this list, which is why the table is per-card: block 17 is 0xFA000
    on an 8 Mbit card and 0x110000 on a 16 Mbit one. Same map as
    Machine::flash_build_blocks -- two copies of one truth is how they drift apart, so
    tests/test_hle_bios_flash.py checks this list against the core's."""
    out = []
    off = 0
    while off + 0x10000 <= capacity - 0x10000:
        out.append(off)
        off += 0x10000
    top = capacity - 0x10000
    return out + [top, top + 0x8000, top + 0xA000, top + 0xC000]


def gen():
    out = []
    A = out.append
    A(";***************************************************************")
    A(";  NgpCraft Emulator - clean-room HLE BIOS image (M0)  [GENERATED]")
    A(";  Loaded via ngpc_load_bios when no real bios.bin is present.")
    A(";  Clean-room: reproduces the hardware/SDK CONTRACT, not SNK bytes.")
    A(";***************************************************************")
    A("\t$MAXIMUM")
    A("\tmodule\tbios_hle")
    A("")
    A("\tpublic\t_boot")
    A("")
    A(";===============================================================")
    A("f_code\tsection code large align=1,1")
    A(";===============================================================")
    A("")
    A("; --- RESET / power-on : hw vector slot 0 (0xFFFF00) ---")
    A("_boot:")
    A("\tld\txiy, _uvt_stub          ; 45 <stub>   ] ANCHOR the core's")
    A("\tld\txix, 0x00006fb8         ; 44 B8 6F..  ] seed_user_vector_table scans")
    A("\tld\tbc, 18")
    A("_uvt_fill:")
    A("\tldl\t(xix+), xiy")
    A("\tdjnz\tbc, _uvt_fill")
    A("\tldw\t(0x006c7a), 0xa5a5     ; 'booted once' marker")
    A("\t; The INTxx shadows (0x6C24..0x6C2B) are deliberately NOT seeded here. Seeding")
    A("\t; them from the registers was tried and measured: this code runs during the")
    A("\t; warm-up, BEFORE the hand-off writes INTE45, so it copied zeros -- and the")
    A("\t; retail BIOS leaves them at zero too (89 of 90 ROMs). Zero is the match.")
    A("\t; preload the clean-room font into CHAR RAM (the warm-up captures it,")
    A("\t; the hand-off installs it) -- games that SYSFONTSET find it present.")
    A("\tld\txix, _font_data")
    A("\tld\txiy, 0x0000a000")
    A("\tld\tbc, 0x0400              ; 0x1000 bytes / 4")
    A("_font_copy:")
    A("\tldl\txwa, (xix+)")
    A("\tldl\t(xiy+), xwa")
    A("\tdjnz\tbc, _font_copy")
    A("_boot_idle:")
    A("\thalt")
    A("\tjr\t_boot_idle")
    A("")
    A("; --- default user-vector stub (bare RETI) ---")
    A("_uvt_stub:")
    A("\treti")
    A("")
    A("; --- generic unused-interrupt stub ---")
    A("_reti:")
    A("\treti")
    A("")
    A("; --- swi 1 : BIOS system-call trap. Dispatch through SYSCALL_TBL, same as")
    A(";  the SDK's SYSTEM_CALL wrapper -- some games (Card Fighters Clash 2) call")
    A(";  INTLVSET via `swi 1` directly, not the wrapper. ldf 3 makes W == RW3.")
    A(";  We emulate `call (stub)` with a push/RET (asm900 rejects `call (reg)`),")
    A(";  the stub returns via RET, then we RETI back to the caller.")
    A(";")
    A(";  !! THE DISPATCHER MUST NOT EAT THE ARGUMENTS. This used to do its table")
    A(";  lookup in XHL and park the return address in XDE -- but XHL3 and XDE3 ARE")
    A(";  arguments: FLASHWRITE takes the source in XHL3 and the offset in XDE3,")
    A(";  RTCGET takes its buffer in XHL3. So a save through `swi 1` programmed from")
    A(";  the dispatcher's own address, and every byte went nowhere. The SDK wrapper")
    A(";  gets this right by using XIX; we do the same, and park what XIX cannot hold")
    A(";  in BIOS work RAM. Only W (the vector number, already consumed) is clobbered.")
    A("SWI_SAVED_XIX\tequ\t0x006c44")
    A("SWI_STUB\tequ\t0x006c48")
    A("_swi1:")
    A("\tldf\t3                     ; W = RW3 = vector index")
    A("\tldl\t(SWI_SAVED_XIX), xix   ; the game's XIX -- restored before the stub runs")
    A("\tadd\tw, w")
    A("\tadd\tw, w                   ; W = index * 4")
    A("\tld\txix, 0x00fffe00")
    A("\tldl\txix, (xix+w)           ; XIX = SYSCALL_TBL[index]")
    A("\tldl\t(SWI_STUB), xix")
    A("\tld\txix, _swi1_after        ; return address, pushed UNDER the target")
    A("\tpush\txix")
    A("\tldl\txix, (SWI_STUB)")
    A("\tpush\txix                   ; target on top: RET jumps to the stub")
    A("\tldl\txix, (SWI_SAVED_XIX)")
    A("\tret                            ; -> stub (returns via RET to _swi1_after)")
    A("_swi1_after:")
    A("\treti")
    A("")
    A(";  Syscall stubs reached by a DIRECT table CALL -- the SDK's SYSTEM_CALL")
    A(";  wrapper (calr, not swi 1): it does ldf 3 then `call (0xFFFE00 + RW3*4)`,")
    A(";  so a stub runs in bank 3 and returns via RET. Commercial COM-heavy games")
    A(";  (Nige-Ron-Pa, Koi Koi, KOF-BdP) DRAIN the serial RX with COMGETDATA until")
    A(";  RA3==1 ('no more data'); with no cable the real BIOS returns 1 at once.")
    A("_sc_ret:")
    A("\tret                            ; default: leave registers as-is")
    A("_sc_nodata:")
    A("\tldw\twa, 0x0101              ; RA3=1 (and RW3=1): 'buffer empty / no data'")
    A("\tret")
    A("_sc_zero:")
    A("\tldw\twa, 0x0000              ; RWA3=0: COM*STATUS = no error, no data")
    A("\tret")
    A(";  RTCGET: copy 7 packed-BCD clock bytes (year,month,day,hour,min,sec,")
    A(";  weekday) from the RTC I/O regs 0x91-0x97 into the caller's buffer at")
    A(";  XHL3. The core routes 0x90-0x9A reads to its seeded RTC. WA/XHL preserved.")
    A("_sc_rtcget:")
    A("\tpush\twa")
    A("\tpush\txhl")
    for reg in range(0x91, 0x98):
        A(f"\tldb\ta, ({reg:#04x})")
        A("\tldb\t(xhl+), a")
    A("\tpop\txhl")
    A("\tpop\twa")
    A("\tret")
    A(";  INTLVSET: set interrupt source's priority in the INTxx I/O regs. Bank 3:")
    A(";  C=source(0..9), B=level. MEASURED from the retail BIOS (5 games): the")
    A(";  written nibble = 0x08 | min(level&7,5) -- the 0x08 is the ENABLE bit the")
    A(";  Python ref omits. Even source -> low nibble, odd -> high; reg from table.")
    A(";  ---------------- THE SAVE: a real flash driver, not a stub ----------------")
    A(";  A Neo Geo Pocket has no save RAM: a game saves by ERASING a block of its own")
    A(";  cartridge and PROGRAMMING its slot back in, and it asks the BIOS to do it.")
    A(";  These four vectors used to fall through to `_sc_ret`, which left RA3 holding")
    A(";  the CARD NUMBER the caller passed (0) -- read back as SYS_SUCCESS. So every")
    A(";  save reported success and wrote NOTHING. A save that fails loudly is bad; a")
    A(";  save that fails silently is how a player loses a file and never knows why.")
    A(";")
    A(";  So the driver is the real thing: the AMD/Fujitsu command cycles at the cart")
    A(";  window, which is exactly what the chip in cpp/src/memory.cpp implements.")
    A(";      unlock  AA @ 0x205555 . 55 @ 0x202AAA . then")
    A(";              A0 @ 0x205555  program: the NEXT write IS the data")
    A(";              80 . unlock again . 30 @ block  erase that block")
    A(";              80 . unlock again . 10 @ 5555   erase the whole chip")
    A(";              9A . unlock again . 9A @ block  protect it (irreversible)")
    A(";  After an erase the chip answers ONE read and is memory again -- that read is")
    A(";  what a driver's status poll consumes, and we MUST consume it too: leave it")
    A(";  pending and the game's next instruction fetch from the cart reads 0xFF.")
    A(";")
    A(";  TWO SLOTS, AND THE SECOND ONE IS NOT ALWAYS EMPTY. Card 0 is 0x200000 and")
    A(";  card 1 is 0x800000. On a 2 MiB cartridge that second window is the")
    A(";  DEVELOPMENT slot and a production console has nothing in it -- but a 4 MiB")
    A(";  cartridge is TWO DIES and the second one lives exactly there. Measured: with")
    A(";  Metal Slug 2nd Mission, Densha de Go! 2 or SvC Match of the Millennium in the")
    A(";  slot, the retail BIOS writes 0x6C59 = 3. Refusing card 1 outright -- which is")
    A(";  what this driver did -- fails a save on the very carts that have two chips.")
    A(";  So the test is not the card NUMBER but whether that slot holds a cartridge,")
    A(";  which is precisely what the card-type byte says.")
    A("CARD_TYPE0\tequ\t0x006c58")
    A("UNLOCK1_CARD0\tequ\t0x00205555      ; +0x600000 for card 1")
    A("UNLOCK_DELTA\tequ\t0x2aab           ; 0x5555 - 0x2AAA")

    def unlock2():
        """AA @ 5555, 55 @ 2AAA -- the two cycles that open every command.

        Addressed through XIY (= this card's 0x5555) instead of an absolute, so the
        same code drives either die. The second unlock address is one displacement
        away, which saves carrying a second pointer."""
        A("\tldb\ta, 0xaa")
        A("\tldb\t(xiy), a")
        A("\tldb\ta, 0x55")
        A("\tldb\t(xiy-UNLOCK_DELTA), a")

    def unlock(prefix):
        """...followed by the command byte at 5555."""
        unlock2()
        A(f"\tldb\ta, {prefix}")
        A("\tldb\t(xiy), a")

    def card_slot(tag):
        """RA3 (0 or 1) -> XIY = that card's unlock address, and refuse a slot with no
        cartridge in it. Written inline per stub rather than as a shared exit: `jr` is
        a SHORT relative branch and the block tables push the stubs apart -- a shared
        label assembles until it doesn't (ASM900-Error-227)."""
        A("\tpush\txde")
        A("\tldl\txiy, UNLOCK1_CARD0")
        A("\tcp\ta, 0")
        A(f"\tjr\tz, _{tag}_slot0")
        A("\tcp\ta, 1")
        A(f"\tjr\tnz, _{tag}_no_card")
        A("\tldl\txde, 0x00600000         ; card 1 sits 6 MiB further up")
        A("\taddl\txiy, xde")
        A(f"_{tag}_slot0:")
        A("\tldl\txde, 0")
        A("\tldb\te, a                    ; card-type byte is 0x6C58 + card")
        A("\tpush\txhl")
        A("\tldl\txhl, CARD_TYPE0")
        A("\taddl\txhl, xde")
        A("\tldb\te, (xhl)                ; ...and E now holds that card's TYPE")
        A("\tpop\txhl")
        A("\tcp\te, 0")
        A(f"\tjr\tz, _{tag}_no_card")
        A("\tldb\t(FL_CARD), a           ; the slot this call is for")
        A("\tpop\txde")
        A(f"\tjr\t_{tag}_card_ok")
        A(f"_{tag}_no_card:")
        A("\tpop\txde")
        A("\tldb\ta, 0xff                 ; nothing in that slot")
        A("\tret")
        A(f"_{tag}_card_ok:")

    A(";  Block number -> absolute address. A game erases by BLOCK NUMBER, and the")
    A(";  number->address table is the CARD's (SDK FlashMem.txt / BLOCK_NO.INC), so it")
    A(";  is chosen by that card's type byte -- 0x6C58 for card 0, 0x6C59 for card 1,")
    A(";  the same bytes the retail BIOS reads. The tables hold card 0's addresses;")
    A(";  card 1 is the same map 6 MiB further up. In: B = block, FL_CARD = the slot.")
    A(";  Out: XDE = address, A = 0 ok / 0xFF bad.")
    A("FL_CARD\tequ\t0x006c4c              ; which slot the call in flight is for")
    A("_fl_block_addr:")
    A("\tpush\txhl")
    A("\tldl\txde, 0")
    A("\tldb\ta, (FL_CARD)")
    A("\tldb\te, a")
    A("\tldl\txhl, CARD_TYPE0")
    A("\taddl\txhl, xde")
    A("\tldb\ta, (xhl)                 ; this card's type")
    A("\tpop\txhl")
    A("\tcp\ta, 1")
    A("\tjr\tz, _flba_4m")
    A("\tcp\ta, 2")
    A("\tjr\tz, _flba_8m")
    A("\tcp\ta, 3")
    A("\tjr\tz, _flba_16m")
    A("\tldb\ta, 0xff                 ; card type 0: no cartridge")
    A("\tret")
    A("_flba_4m:")
    A("\tldl\txhl, _blk_4m")
    A("\tldb\ta, 11")
    A("\tjr\t_flba_go")
    A("_flba_8m:")
    A("\tldl\txhl, _blk_8m")
    A("\tldb\ta, 19")
    A("\tjr\t_flba_go")
    A("_flba_16m:")
    A("\tldl\txhl, _blk_16m")
    A("\tldb\ta, 35")
    A("_flba_go:")
    A("\tcp\tb, a")
    A("\tjr\tnc, _flba_bad            ; block past the end of this card")
    A("\tldl\txde, 0")
    A("\tldb\te, b")
    A("\tsll\t2, e                    ; 4 bytes per entry (35 blocks max -> 140)")
    A("\taddl\txhl, xde")
    A("\tldl\txde, (xhl)")
    A("\tldb\ta, (FL_CARD)")
    A("\tcp\ta, 1")
    A("\tjr\tnz, _flba_ok")
    A("\tpush\txhl")
    A("\tldl\txhl, 0x00600000         ; the second die's window")
    A("\taddl\txde, xhl")
    A("\tpop\txhl")
    A("_flba_ok:")
    A("\tldb\ta, 0")
    A("\tret")
    A("_flba_bad:")
    A("\tldb\ta, 0xff")
    A("\tret")
    A(";  FLASHERS (8): erase one block. In: RA3 = card, RB3 = block.")
    A("_sc_flashers:")
    card_slot("fe")
    A("\tpush\txhl")
    A("\tpush\txde")
    A("\tcalr\t_fl_block_addr")
    A("\tcp\ta, 0")
    A("\tjr\tnz, _fe_bad")
    unlock("0x80")
    unlock2()
    A("\tldb\ta, 0x30                 ; erase the block containing this address")
    A("\tldb\t(xde), a")
    A(";  AND THEN IT WAITS, because the chip is BUSY -- about ten milliseconds for")
    A(";  an 8 KB block, during which the window answers status instead of contents.")
    A(";  This used to be a single read, 'consume the chip's one-shot done', which was")
    A(";  only ever true of a model where an erase costs nothing. Against a chip that")
    A(";  takes time, that read returns status and the routine walks off with the block")
    A(";  still erasing. DQ5 is the chip saying it gave up -- without it, a poll on a")
    A(";  block that cannot erase never ends.")
    A("\tpush\txiz")
    A("\tldl\txiz, 0                  ; the poll's own ceiling: DQ5 may never come")
    A("_fe_poll:")
    A("\tldb\ta, (xde)")
    A("\tcp\ta, 0xff                  ; blank yet?")
    A("\tjr\tz, _fe_erased")
    A("\tbit\t5, (xde)                ; DQ5, if this part has it")
    A("\tjr\tnz, _fe_gave_up")
    A("\tincl\t1, xiz")
    A("\tcpl\txiz, 0x001fffff         ; same ceiling as the AMD stub the games ship")
    A("\tjr\tnz, _fe_poll")
    A("_fe_gave_up:")
    A("\tldb\ta, (xde)                ; one last look before believing it")
    A("\tcp\ta, 0xff")
    A("\tjr\tz, _fe_erased")
    A("\tldb\ta, 0xf0                 ; reset the chip, then say the erase failed")
    A("\tldb\t(xiy), a")
    A("\tpop\txiz")
    A("\tpop\txde")
    A("\tpop\txhl")
    A("\tldb\ta, 0xff")
    A("\tret")
    A("_fe_erased:")
    A("\tpop\txiz")
    A("\tpop\txde")
    A("\tpop\txhl")
    A("\tldb\ta, 0                    ; SYS_SUCCESS")
    A("\tret")
    A("_fe_bad:")
    A("\tpop\txde")
    A("\tpop\txhl")
    A("\tldb\ta, 0xff")
    A("\tret")
    A(";  FLASHALLERS (7): erase the WHOLE chip. In: RA3 = card.")
    A("_sc_flashallers:")
    card_slot("fa")
    unlock("0x80")
    unlock2()
    A("\tldb\ta, 0x10")
    A("\tldb\t(xiy), a")
    A("\tldb\ta, (xiy)                 ; consume the 'done'")
    A("\tldb\ta, 0")
    A("\tret")
    A(";  (FLASHPROTECT is vector 0x0D, not 9 -- 9 is ALARMSET. It lives further down,")
    A(";   with the ABI SYSTEM.INC actually documents.)")
    A(";  FLASHWRITE (6): program data into the cart. In: RA3 = card, RBC3 = length in")
    A(";  256-byte units, XHL3 = source, XDE3 = OFFSET in the card (not an address).")
    A(";  SysCall.txt: destroys RBC3/XHL3/XDE3. Each byte needs its own unlock+A0: a")
    A(";  NOR cell only goes DOWN, so the block must have been erased first -- which is")
    A(";  why a game always calls FLASHERS before this one.")
    A("_sc_flashwrite:")
    card_slot("fw")
    A("\tpush\txiy")
    A("\tldl\txiy, 0x00200000")
    A("\taddl\txde, xiy                ; offset -> absolute destination, card 0...")
    A("\tpop\txiy")
    A("\tpush\txwa")
    A("\tldb\ta, (FL_CARD)")
    A("\tcp\ta, 1")
    A("\tjr\tnz, _fw_based")
    A("\tpush\txhl")
    A("\tldl\txhl, 0x00600000         ; ...or the second die, 6 MiB further up")
    A("\taddl\txde, xhl")
    A("\tpop\txhl")
    A("_fw_based:")
    A("\tpop\txwa")
    A("\tcp\tbc, 0")
    A("\tjr\tz, _fw_none              ; zero units: nothing pushed, nothing to pop")
    A("\tpush\txiz                    ; the poll's own ceiling lives here")
    A("_fw_unit:")
    A("\tldb\tw, 0                    ; 256 bytes per unit (djnz: 0 -> 255 -> ... -> 0)")
    A("_fw_byte:")
    A("\tldl\txiz, 0")
    unlock("0xa0")
    A("\tldb\ta, (xhl+)               ; the cycle after A0 IS the data")
    A("\tldb\t(xde), a")
    A(";  ONE BYTE, THEN WAIT FOR IT. The chip is busy for the whole program time and")
    A(";  answers status, not contents -- so it is not listening for the next byte's")
    A(";  unlock either. Firing all 256 bytes back to back, which is what this loop did")
    A(";  before, lands roughly one byte in four and reports success: measured, exactly")
    A(";  that. Silicon's own routine polls between bytes, and so does this one now.")
    A(";  AND THE POLL NEEDS ITS OWN CEILING, because the chip may never answer at all.")
    A(";  Measured on the cartridge (hw_test_flash_timing, ROW 9): a 1 asked over a 0 --")
    A(";  a slot programmed twice with no erase between -- draws NO DQ5 in 2.45 seconds.")
    A(";  The datasheets say DQ5; this part does not do it. So DQ5 is still honoured if")
    A(";  it comes, and the count is what actually gets us out. Same ceiling as the AMD")
    A(";  stub the games ship, 0x3FFFF turns, for the same reason.")
    A("_fw_poll:")
    A("\tcp\ta, (xde)                 ; DQ7 comes back true only when it has landed")
    A("\tjr\tz, _fw_landed")
    A("\tbit\t5, (xde)                ; DQ5, if this part has it")
    A("\tjr\tnz, _fw_gave_up")
    A("\tincl\t1, xiz")
    A("\tcpl\txiz, 0x0003ffff")
    A("\tjr\tnz, _fw_poll")
    A("_fw_gave_up:")
    A("\tcp\ta, (xde)                 ; one last look before believing it")
    A("\tjr\tz, _fw_landed")
    A("\tldb\ta, 0xf0                 ; reset the chip, then say the write failed")
    A("\tldb\t(xiy), a")
    A("\tpop\txiz")
    A("\tldb\ta, 0xff")
    A("\tret")
    A("_fw_landed:")
    A("\tincl\t1, xde")
    A("\tdjnz\tw, _fw_byte")
    A("\tdjnz\tbc, _fw_unit")
    A("\tpop\txiz")
    A("_fw_none:")
    A("\tldb\ta, 0")
    A("\tret")
    A(";  ---------------- the rest of the BIOS's documented surface ----------------")
    A(";  Vector numbers are SYSTEM.INC's, which is the authority. Reading them off")
    A(";  another doc put FLASHPROTECT on 9 -- and 9 is ALARMSET, so a game setting an")
    A(";  alarm would have IRREVERSIBLY protected a flash block instead. Measured")
    A(";  against the corpus, ranked by how many games knock on each door.")
    A(";")
    A(";  SHUTDOWN (0x00): the console switched off. Masking every interrupt and")
    A(";  halting IS off as far as the core is concerned (core.cpp: 'the halt is not a")
    A(";  hang, it is the console switched off').")
    A("_sc_shutdown:")
    A("\tei\t7                      ; nothing can wake it")
    A("_sd_off:")
    A("\thalt")
    A("\tjr\t_sd_off")
    A(";  GEMODESET (0x0E, 19 games): RA3 = 0 (K1GE) / 0x10 (K2GE). The mode register is")
    A(";  write-PROTECTED -- 0xAA to 0x87F0 opens it, 0x55 closes it again -- which is")
    A(";  why a plain store to 0x87E2 does nothing and this has to be a real routine.")
    A("_sc_gemodeset:")
    A("\tpush\txde")
    A("\tldb\te, a                   ; remember the requested mode")
    A("\tldb\ta, 0xaa")
    A("\tldb\t(0x0087f0), a          ; unlock")
    A("\tldb\ta, e")
    A("\tcp\ta, 0")
    A("\tjr\tnz, _gms_colour")
    A("\tldb\ta, 0x80                ; K1GE compatible: upper-palette mode")
    A("\tjr\t_gms_write")
    A("_gms_colour:")
    A("\tldb\ta, 0                   ; K2GE native")
    A("_gms_write:")
    A("\tldb\t(0x0087e2), a")
    A("\tldb\ta, e")
    A("\tldb\t(0x006f95), a          ; the system colour-mode flag games read")
    A("\tldb\ta, 0x55")
    A("\tldb\t(0x0087f0), a          ; re-lock")
    A("\tpop\txde")
    A("\tldb\ta, 0")
    A("\tret")
    A(";  SYSFONTSET (0x05, 17 games): copy the 256 system characters to CHAR RAM at")
    A(";  0xA000. RA3 picks the palette codes -- low nibble for the glyph, high nibble")
    A(";  for the background -- and honouring them is the difference between a legible")
    A(";  dialogue box and an invisible one.")
    A(";")
    A(";  The stored font is 2bpp with glyph = 3 and background = 0, so every 2-bit")
    A(";  field is 11 or 00 and the source byte IS the glyph mask. That turns the")
    A(";  recolour into four byte ops with no table:")
    A(";      out = (src AND fg*0x55) OR (NOT src AND bg*0x55)")
    A("_sc_sysfontset:")
    A("\tpush\txhl")
    A("\tpush\txde")
    A("\tpush\txbc")
    A("\tpush\txix")
    A("\tpush\txiy")
    A("\tldb\te, a")
    A("\tandb\te, 0x0f                ; glyph palette code")
    A("\tldb\td, e")
    A("\tsll\t2, d")
    A("\torb\te, d")
    A("\tldb\td, e")
    A("\tsll\t4, d")
    A("\torb\te, d                    ; E = code repeated in all four fields")
    A("\tsrl\t4, a")
    A("\tandb\ta, 0x0f                ; background palette code")
    A("\tldb\tc, a")
    A("\tldb\td, c")
    A("\tsll\t2, d")
    A("\torb\tc, d")
    A("\tldb\td, c")
    A("\tsll\t4, d")
    A("\torb\tc, d                    ; C = the same, for the background")
    A("\tldl\txix, _font_data")
    A("\tldl\txiy, 0x0000a000")
    A("\tldw\thl, 0x1000")
    A("_sfs_loop:")
    A("\tldb\ta, (xix+)")
    A("\tldb\td, a")
    A("\tandb\td, e                   ; glyph pixels take the glyph code")
    A("\txorb\ta, 0xff")
    A("\tandb\ta, c                   ; the rest take the background code")
    A("\torb\ta, d")
    A("\tldb\t(xiy+), a")
    A("\tdecw\t1, hl")
    A("\tjr\tnz, _sfs_loop")
    A("\tpop\txiy")
    A("\tpop\txix")
    A("\tpop\txbc")
    A("\tpop\txde")
    A("\tpop\txhl")
    A("\tldb\ta, 0")
    A("\tret")
    A(";  ALARMSET (0x09) / ALARMDOWNSET (0x0B): the RTC alarm. QC3 = day, RB3 = hour,")
    A(";  RC3 = minute, 0xFF meaning 'any'. Same registers either way -- the SDK's two")
    A(";  names are 'while the game runs' and 'wake the console up', and this console")
    A(";  keeps its clock running on the coin cell either way.")
    A(";")
    A(";  The chip has NO wildcard except day 0 = every day, so the SDK's 0xFF day is")
    A(";  normalised here, exactly as the retail BIOS does before it touches the chip.")
    A(";  Arming also has to let INT0 through (INTE0, enable bit 0x08 + level), or the")
    A(";  alarm would fire into a masked pin and nothing would happen.")
    A("_sc_alarmset:")
    A("_sc_alarmdownset:")
    A("\tldb\ta, qc                   ; day")
    A("\tcp\ta, 0xff")
    A("\tjr\tz, _als_anyday")
    A("\tcp\ta, 0x01")
    A("\tjr\tc, _als_bad")
    A("\tcp\ta, 0x32                  ; packed BCD: 0x31 is the last day")
    A("\tjr\tnc, _als_bad")
    A("\tjr\t_als_setday")
    A("_als_anyday:")
    A("\tldb\ta, 0                    ; the chip's 'every day'")
    A("_als_setday:")
    A("\tldb\t(0x000098), a")
    A("\tldb\ta, b                    ; hour")
    A("\tcp\ta, 0xff")
    A("\tjr\tz, _als_sethour")
    A("\tcp\ta, 0x24")
    A("\tjr\tnc, _als_bad")
    A("_als_sethour:")
    A("\tldb\t(0x000099), a")
    A("\tldb\ta, c                    ; minute")
    A("\tcp\ta, 0xff")
    A("\tjr\tz, _als_setmin")
    A("\tcp\ta, 0x60")
    A("\tjr\tnc, _als_bad")
    A("_als_setmin:")
    A("\tldb\t(0x00009a), a")
    A("\tldb\ta, (0x000090)")
    A("\torb\ta, 0x02                 ; arm the alarm, leave the clock running")
    A("\tldb\t(0x000090), a")
    A("\tldb\ta, (0x000070)")
    A("\tandb\ta, 0xf0")
    A("\torb\ta, 0x0c                 ; INT0: enable bit 0x08 | level 4")
    A("\tldb\t(0x000070), a")
    A("\tldb\ta, 0")
    A("\tret")
    A("_als_bad:")
    A("\tldb\ta, 0xff                 ; SYS_FAILURE")
    A("\tret")
    A(";  FLASHPROTECT (0x0D): RB3 = first block, RC3 = card type (0=4M, 1=8M, 2=16M),")
    A(";  RD3 = how many. Irreversible on silicon ('there is no operation which will")
    A(";  remove the protection'), so it is passed through to the chip rather than")
    A(";  faked -- but note the core does not PERSIST protection (specs/FLASH.md 5),")
    A(";  so it lasts until the cartridge is reloaded.")
    A("_sc_flashprotect:")
    A("\tpush\txhl")
    A("\tpush\txde")
    A("\tpush\txix")
    A("\tpush\txiy")
    A("\tldl\txiy, UNLOCK1_CARD0       ; card 0: SYSTEM.INC's ABI has no slot argument")
    A("\tldl\txhl, _blk_4m")
    A("\tcp\tc, 0")
    A("\tjr\tz, _fp_have")
    A("\tldl\txhl, _blk_8m")
    A("\tcp\tc, 1")
    A("\tjr\tz, _fp_have")
    A("\tldl\txhl, _blk_16m")
    A("\tcp\tc, 2")
    A("\tjr\tz, _fp_have")
    A("\tpop\txiy")
    A("\tpop\txix")
    A("\tpop\txde")
    A("\tpop\txhl")
    A("\tldb\ta, 0xff                 ; not one of the three cards")
    A("\tret")
    A("_fp_have:")
    A("\tldl\txix, xhl                ; XIX = the card's block table")
    A("_fp_loop:")
    A("\tcp\td, 0                     ; RD3 blocks still to do")
    A("\tjr\tz, _fp_done")
    A("\tldl\txhl, xix")
    A("\tldl\txde, 0")
    A("\tldb\te, b")
    A("\tsll\t2, e")
    A("\taddl\txhl, xde")
    A("\tldl\txde, (xhl)              ; XDE = that block's address")
    unlock("0x9a")
    unlock2()
    A("\tldb\ta, 0x9a")
    A("\tldb\t(xde), a")
    A("\tincb\t1, b")
    A("\tdecb\t1, d")
    A("\tjr\t_fp_loop")
    A("_fp_done:")
    A("\tpop\txiy")
    A("\tpop\txix")
    A("\tpop\txde")
    A("\tpop\txhl")
    A("\tldb\ta, 0")
    A("\tret")
    A(";  ---------------- THE LINK CABLE: the COM ring machinery ----------------")
    A(";  Serial channel 0 IS the link cable. The core models the wire (a byte pipe)")
    A(";  and the silicon around it; the BIOS owns everything above:")
    A(";")
    A(";    write SC0BUF (0x50) -> one baud-time later the byte is on the wire and")
    A(";                           vector 0x19 fires: pull the NEXT byte from the ring")
    A(";    a byte arrives      -> it is presented at SC0BUF and vector 0x18 fires:")
    A(";                           read it into the RX ring")
    A(";    RTS = 0xB2 bit 0    -> LOW means 'ready to receive'; a byte is held on the")
    A(";                           peer's side while it is high (that is the handshake)")
    A(";")
    A(";  !! THE TWO SERIAL VECTORS ARE CROSS-WIRED versus their SDK names: 0x18 is")
    A(";  named INTTX0 and RECEIVES, 0x19 is named INTRX0 and TRANSMITS. That is what")
    A(";  the retail BIOS's own handlers do, and the core raises them BY BEHAVIOUR")
    A(";  (machine.hpp). Wiring them by name gives you a console that receives its own")
    A(";  transmitted byte -- a self-loopback that looks like it works.")
    A(";")
    A(";  The ring ADDRESSES are ABI, not an implementation detail: the SDK's own")
    A(";  serial code -- and tests/roms/link_probe_main.c -- read the RX count at")
    A(";  0x6D01 directly to know how many bytes to drain.")
    A("COM_TXRING\tequ\t0x006c80          ; 64 bytes")
    A("COM_RXRING\tequ\t0x006cc0          ; 64 bytes")
    A("COM_TXCNT\tequ\t0x006d00")
    A("COM_RXCNT\tequ\t0x006d01           ; <- games read this one themselves")
    A("COM_TXHEAD\tequ\t0x006d02")
    A("COM_TXTAIL\tequ\t0x006d03")
    A("COM_RXHEAD\tequ\t0x006d04")
    A("COM_RXTAIL\tequ\t0x006d05")
    A("COM_TXBUSY\tequ\t0x006d06")
    A("SC0BUF\tequ\t0x000050")
    A("INTES0\tequ\t0x000077")
    A("PORT_RTS\tequ\t0x0000b2")
    A(";  Hand the next queued byte to the shift register, or mark the transmitter")
    A(";  idle. Shared by COMSENDSTART (starts the chain) and the TX ISR (continues")
    A(";  it) -- one pump, so a byte cannot be sent twice or dropped between them.")
    A(";  Clobbers WA; callers that need it save it.")
    A("_tx_pump:")
    A("\tpush\txix")
    A("\tpush\tsr")
    A("\tei\t7                        ; COMSENDSTART reaches this from the main loop,")
    A("\t                             ; where the TX interrupt can land mid-update")
    A("\tldb\ta, (COM_TXCNT)")
    A("\tcp\ta, 0")
    A("\tjr\tz, _txp_idle")
    A("\tldl\txix, COM_TXRING")
    A("\tldb\tw, (COM_TXTAIL)")
    A("\tldb\ta, (xix+w)")
    A("\tldb\t(SC0BUF), a              ; on the wire after one baud-time")
    A("\taddb\tw, 1")
    A("\tandb\tw, 0x3f")
    A("\tldb\t(COM_TXTAIL), w")
    A("\tldb\ta, (COM_TXCNT)")
    A("\tdecb\t1, a")
    A("\tldb\t(COM_TXCNT), a")
    A("\tldb\ta, 1")
    A("\tldb\t(COM_TXBUSY), a")
    A("\tpop\tsr")
    A("\tpop\txix")
    A("\tret")
    A("_txp_idle:")
    A("\tldb\ta, 0")
    A("\tldb\t(COM_TXBUSY), a")
    A("\tpop\tsr")
    A("\tpop\txix")
    A("\tret")
    A("; --- serial ISRs. These do NOT chain to a user vector slot: the COM rings are")
    A(";  the BIOS's own, and the retail BIOS takes these two vectors over as well.")
    A("_isr_ser_rx:                     ; vector 0x18 -- a byte ARRIVED")
    A("\tpush\txwa")
    A("\tpush\txix")
    A("\tldb\ta, (SC0BUF)              ; reading it is also what clears the byte")
    A("\tldb\tw, (COM_RXCNT)")
    A("\tcp\tw, 64")
    A("\tjr\tnc, _isr_rx_full          ; ring full: the byte is lost, as on silicon")
    A("\tldl\txix, COM_RXRING")
    A("\tldb\tw, (COM_RXHEAD)")
    A("\tldb\t(xix+w), a")
    A("\taddb\tw, 1")
    A("\tandb\tw, 0x3f")
    A("\tldb\t(COM_RXHEAD), w")
    A("\tldb\ta, (COM_RXCNT)")
    A("\tincb\t1, a")
    A("\tldb\t(COM_RXCNT), a")
    A("_isr_rx_full:")
    A("\tpop\txix")
    A("\tpop\txwa")
    A("\treti")
    A("_isr_ser_tx:                     ; vector 0x19 -- the wire is free again")
    A("\tpush\txwa")
    A("\tpush\txix")
    A("\tcalr\t_tx_pump")
    A("\tpop\txix")
    A("\tpop\txwa")
    A("\treti")
    A(";  COMINIT (0x10): rings empty, both serial vectors at level 6 in INTES0, and")
    A(";  `ei 6` so they can actually be delivered -- the hand-off leaves the CPU at")
    A(";  IFF 7, which masks everything below it. The retail BIOS does the same `ei 6`")
    A(";  inside its own COM routines.")
    A("_sc_cominit:")
    A("\tldb\ta, 0")
    A("\tldb\t(COM_TXCNT), a")
    A("\tldb\t(COM_RXCNT), a")
    A("\tldb\t(COM_TXHEAD), a")
    A("\tldb\t(COM_TXTAIL), a")
    A("\tldb\t(COM_RXHEAD), a")
    A("\tldb\t(COM_RXTAIL), a")
    A("\tldb\t(COM_TXBUSY), a")
    A("\tldb\ta, 0xee                  ; INTES0: both serial vectors, level 6")
    A("\tldb\t(INTES0), a")
    A("\tei\t6")
    A("\tldb\ta, 0")
    A("\tret")
    A(";  COMSENDSTART (0x11): begin transmitting what CREATEDATA queued. If the")
    A(";  transmitter is already running, the ISR is pulling the ring: do nothing, or")
    A(";  the same byte goes out twice.")
    A("_sc_comsendstart:")
    A("\tldb\ta, (COM_TXBUSY)")
    A("\tcp\ta, 0")
    A("\tjr\tnz, _css_done")
    A("\tcalr\t_tx_pump")
    A("_css_done:")
    A("\tldb\ta, 0")
    A("\tret")
    A(";  COMRECIVESTART (0x12) / COMONRTS (0x15): RTS LOW = ready to receive.")
    A("_sc_comrecvstart:")
    A("_sc_comonrts:")
    A("\tldb\ta, (PORT_RTS)")
    A("\tandb\ta, 0xfe")
    A("\tldb\t(PORT_RTS), a")
    A("\tei\t6")
    A("\tldb\ta, 0")
    A("\tret")
    A(";  COMOFFRTS (0x16): RTS HIGH = hold the peer off.")
    A("_sc_comoffrts:")
    A("\tldb\ta, (PORT_RTS)")
    A("\torb\ta, 0x01")
    A("\tldb\t(PORT_RTS), a")
    A("\tldb\ta, 0")
    A("\tret")
    A(";  --- the two ring primitives -------------------------------------------")
    A(";  Written ONCE and shared by the single-byte and the block syscalls. The two")
    A(";  used to be separate copies of the same six steps, which is how a ring's head")
    A(";  and its count drift apart in one place and not the other.")
    A(";")
    A(";  !! AND THEY RUN WITH INTERRUPTS MASKED. The counts are read-modify-written")
    A(";  from BOTH sides -- COMCREATEDATA increments the one the TX ISR decrements,")
    A(";  COMGETDATA decrements the one the RX ISR increments. An interrupt landing")
    A(";  between the load and the store loses a byte or sends one twice, and the")
    A(";  window is exactly as wide as a serial interrupt is frequent. `push sr` /")
    A(";  `pop sr` restores the caller's mask rather than assuming one.")
    A(";  In: XIX = ring base, XIY = the count byte, XDE = the index byte. Passed as")
    A(";  three pointers rather than one packed record because 0x6D01 (the RX count) is")
    A(";  ABI -- games read it -- so the layout is not ours to rearrange for tidiness.")
    A(";  _ring_put: B -> ring, A = 0 ok / 0xFF full.")
    A(";  _ring_get: ring -> B, A = 0 ok / 1 empty.")
    A("_ring_put:")
    A("\tpush\tsr")
    A("\tei\t7")
    A("\tldb\ta, (xiy)                 ; the count")
    A("\tcp\ta, 64")
    A("\tjr\tnc, _ring_put_full")
    A("\tldb\tw, (xde)                 ; the head")
    A("\tldb\t(xix+w), b")
    A("\taddb\tw, 1")
    A("\tandb\tw, 0x3f")
    A("\tldb\t(xde), w")
    A("\tldb\ta, (xiy)")
    A("\tincb\t1, a")
    A("\tldb\t(xiy), a")
    A("\tpop\tsr")
    A("\tldb\ta, 0")
    A("\tret")
    A("_ring_put_full:")
    A("\tpop\tsr")
    A("\tldb\ta, 0xff                  ; COM_BUF_OVER")
    A("\tret")
    A("_ring_get:")
    A("\tpush\tsr")
    A("\tei\t7")
    A("\tldb\ta, (xiy)")
    A("\tcp\ta, 0")
    A("\tjr\tz, _ring_get_empty")
    A("\tldb\tw, (xde)                 ; the tail")
    A("\tldb\tb, (xix+w)")
    A("\taddb\tw, 1")
    A("\tandb\tw, 0x3f")
    A("\tldb\t(xde), w")
    A("\tldb\ta, (xiy)")
    A("\tdecb\t1, a")
    A("\tldb\t(xiy), a")
    A("\tpop\tsr")
    A("\tldb\ta, 0")
    A("\tret")
    A("_ring_get_empty:")
    A("\tpop\tsr")
    A("\tldb\ta, 1                     ; COM_BUF_EMPTY")
    A("\tret")
    A(";  COMCREATEDATA (0x13): queue RB3. RA3 = 0 (COM_BUF_OK) / 0xFF (COM_BUF_OVER).")
    A("_sc_comcreatedata:")
    A("\tpush\txix")
    A("\tpush\txiy")
    A("\tpush\txde")
    A("\tldl\txix, COM_TXRING")
    A("\tldl\txiy, COM_TXCNT")
    A("\tldl\txde, COM_TXHEAD")
    A("\tcalr\t_ring_put")
    A("\tpop\txde")
    A("\tpop\txiy")
    A("\tpop\txix")
    A("\tret")
    A(";  COMGETDATA (0x14): pop one byte into RB3. RA3 = 0 / 1 (COM_BUF_EMPTY).")
    A(";  Drain loops spin until RA3 == 1, so 'empty' must be exact -- and RW3 is set")
    A(";  to 1 with it, which is what the SDK wrapper's callers compare against.")
    A("_sc_comgetdata:")
    A("\tpush\txix")
    A("\tpush\txiy")
    A("\tpush\txde")
    A("\tldl\txix, COM_RXRING")
    A("\tldl\txiy, COM_RXCNT")
    A("\tldl\txde, COM_RXTAIL")
    A("\tcalr\t_ring_get")
    A("\tpop\txde")
    A("\tpop\txiy")
    A("\tpop\txix")
    A("\tcp\ta, 0")
    A("\tjr\tz, _cgd_done")
    A("\tldw\twa, 0x0101               ; RA3=1 and RW3=1: the drain loop's exit")
    A("_cgd_done:")
    A("\tret")
    A(";  COMSENDSTATUS (0x17) / COMRECIVESTATUS (0x18): RWA3, low byte = how many")
    A(";  bytes are in that buffer (serial.h COM_COUNT_MASK); high bits = errors,")
    A(";  which we never raise -- the cable is a byte pipe with no framing to get wrong.")
    A("_sc_comsendstatus:")
    A("\tldb\tw, 0")
    A("\tldb\ta, (COM_TXCNT)")
    A("\tret")
    A("_sc_comrecvstatus:")
    A("\tldb\tw, 0")
    A("\tldb\ta, (COM_RXCNT)")
    A("\tret")
    A(";  COMCREATEBUFDATA (0x19): queue RB3 bytes from XHL3. RB3 = how many did NOT")
    A(";  fit. COMGETBUFDATA (0x1A): pop up to RB3 bytes into XHL3, RB3 = shortfall.")
    A("_sc_combufsend:")
    A("\tpush\txix")
    A("\tpush\txiy")
    A("\tpush\txde")
    A("\tpush\txhl")
    A("\tldl\txix, COM_TXRING")
    A("\tldl\txiy, COM_TXCNT")
    A("\tldl\txde, COM_TXHEAD")
    A("_cbs_loop:")
    A("\tcp\tb, 0")
    A("\tjr\tz, _cbs_done")
    A("\tldb\ta, (xiy)")
    A("\tcp\ta, 64")
    A("\tjr\tnc, _cbs_done             ; full: RB3 keeps the remainder")
    A("\tpush\txbc")
    A("\tldb\tb, (xhl+)                ; the next source byte, into the ring's argument")
    A("\tcalr\t_ring_put")
    A("\tpop\txbc")
    A("\tdecb\t1, b")
    A("\tjr\t_cbs_loop")
    A("_cbs_done:")
    A("\tpop\txhl")
    A("\tpop\txde")
    A("\tpop\txiy")
    A("\tpop\txix")
    A("\tldb\ta, 0")
    A("\tret")
    A("_sc_combufget:")
    A("\tpush\txix")
    A("\tpush\txiy")
    A("\tpush\txde")
    A("\tpush\txhl")
    A("\tldl\txix, COM_RXRING")
    A("\tldl\txiy, COM_RXCNT")
    A("\tldl\txde, COM_RXTAIL")
    A("_cbg_loop:")
    A("\tcp\tb, 0")
    A("\tjr\tz, _cbg_done")
    A("\tldb\ta, (xiy)")
    A("\tcp\ta, 0")
    A("\tjr\tz, _cbg_done              ; empty: RB3 keeps the shortfall")
    A("\tpush\txbc")
    A("\tcalr\t_ring_get                ; B = the byte")
    A("\tldb\ta, b")
    A("\tpop\txbc")
    A("\tldb\t(xhl+), a")
    A("\tdecb\t1, b")
    A("\tjr\t_cbg_loop")
    A("_cbg_done:")
    A("\tpop\txhl")
    A("\tpop\txde")
    A("\tpop\txiy")
    A("\tpop\txix")
    A("\tldb\ta, 0")
    A("\tret")
    A(";  INTLVSET (0x04): set an interrupt source's priority. Bank 3: C = source (0-9),")
    A(";  B = level. The written nibble is 0x08 | min(level & 7, 5) -- the 0x08 is the")
    A(";  ENABLE bit, measured off the retail BIOS on five games and omitted by the")
    A(";  Python reference model.")
    A(";")
    A(";  !! AND THE REGISTER IS NOT THE SOURCE OF TRUTH -- ITS SHADOW IN RAM IS.")
    A(";  The BIOS keeps a copy of every INTxx register in its work RAM, updates THAT,")
    A(";  and writes the whole byte out. Measured, ten sources x two levels: with")
    A(";  INTE45 (0x71) sitting at 0xDC from the hand-off, INTLVSET(source=1, level=3)")
    A(";  leaves it at 0xB0 -- NOT 0xBC. Read-modify-write of the register would have")
    A(";  kept that 0xC; the retail BIOS discards it, because it never looks at the")
    A(";  register at all. Reading the register back was our bug: it preserved a nibble")
    A(";  silicon would have lost.")
    A(";  source -> shadow:  0,1 -> 0x6C24,0x6C25 | 2,3 -> 0x6C27 | 4,5 -> 0x6C28")
    A(";                     6,7 -> 0x6C2A        | 8,9 -> 0x6C2B")
    A("_sc_intlvset:")
    A("\tpush\txhl")
    A("\tpush\txde")
    A("\tpush\txix")
    A("\tcp\tc, 0x0a")
    A("\tjr\tnc, _intlv_done         ; source > 9: no INTxx register written")
    A("\tldb\ta, b")
    A("\tand\ta, 0x07")
    A("\tcp\ta, 0x06")
    A("\tjr\tc, _intlv_cap")
    A("\tldb\ta, 0x05                ; cap level at 5 (retail BIOS)")
    A("_intlv_cap:")
    A("\tor\ta, 0x08                 ; nibble = 0x08(enable) | level")
    A("\tldl\txde, 0")
    A("\tldl\txhl, _intlv_shadow")
    A("\tldb\te, (xhl+c)")
    A("\tldl\txix, 0x00006c00")
    A("\taddl\txix, xde              ; XIX = this register's shadow byte")
    A("\tldl\txde, 0")
    A("\tldl\txhl, _intlv_reg")
    A("\tldb\te, (xhl+c)             ; XDE = the INTxx I/O address")
    A("\tldb\tl, (xix)               ; the shadow -- what the BIOS believes is in there")
    A("\tbit\t0, c")
    A("\tjr\tz, _intlv_lo            ; even source -> low nibble")
    A("\tsll\t4, a                   ; odd source -> high nibble")
    A("\tand\tl, 0x0f")
    A("\tjr\t_intlv_or")
    A("_intlv_lo:")
    A("\tand\tl, 0xf0")
    A("_intlv_or:")
    A("\tor\tl, a")
    A("\tldb\t(xix), l               ; the shadow is updated first...")
    A("\tldb\t(xde), l               ; ...and the whole byte goes to the register")
    A("_intlv_done:")
    A("\tpop\txix")
    A("\tpop\txde")
    A("\tpop\txhl")
    A("\tret")
    A("_intlv_reg:")
    A("\tdb\t0x70,0x71,0x73,0x73,0x74,0x74,0x79,0x79,0x7a,0x7a")
    A("_intlv_shadow:                 ; low byte of the shadow address (base 0x6C00)")
    A("\tdb\t0x24,0x25,0x27,0x27,0x28,0x28,0x2a,0x2a,0x2b,0x2b")
    A("")
    A(";  The manufacturer's block map, one table per card (SDK FlashMem.txt): 64 KiB")
    A(";  blocks all the way up, and the LAST 64 KiB split 32 / 8 / 8 / 16. The small")
    A(";  blocks at the top are where every save lives -- that split exists so that")
    A(";  rewriting one save slot does not cost 64 KiB. Absolute addresses, card 0.")
    for name, cap in (("_blk_4m", 0x080000), ("_blk_8m", 0x100000), ("_blk_16m", 0x200000)):
        A(f"{name}:")
        for off in card_block_offsets(cap):
            A(f"\tdl\t{0x200000 + off:#010x}")
    A("")
    A(";  Register-preserving indirect jump used by every ISR trampoline:")
    A(";  save XWA to BIOS scratch RAM, push the user-handler address, restore")
    A(";  XWA, RET -> jumps to the handler with the interrupt frame intact and")
    A(";  every register unchanged. No stack turd, no unsupported EX/CALL form.")
    A("SCRATCH\tequ\t0x006c40")
    A("")
    A("; --- VBlank ISR : latch controller into Sys_Lever, then chain ---")
    A("_isr_vblank:")
    A("\tldl\t(SCRATCH), xwa        ; save XWA")
    A("\tldb\ta, (0x0000b0)          ; controller port")
    A("\tldb\t(0x006f82), a          ; -> Sys_Lever (games read this)")
    A("\tldl\txwa, (0x00006fcc)      ; user VBlank handler")
    A("\tpush\txwa")
    A("\tldl\txwa, (SCRATCH)         ; restore XWA")
    A("\tret                            ; -> user handler (it RETIs)")
    A("")
    A("; --- chain trampolines: forward IRQ to the game's user handler ---")
    # emit one chain routine per user-hooked vector (except vblank, above)
    chain_label = {}
    for idx, slot in sorted(USER_SLOT.items()):
        if idx == 11:
            chain_label[idx] = "_isr_vblank"
            continue
        lbl = f"_chain_{idx:02d}"
        chain_label[idx] = lbl
        A(f"{lbl}:")
        A("\tldl\t(SCRATCH), xwa")
        A(f"\tldl\txwa, ({slot:#08x})")
        A("\tpush\txwa")
        A("\tldl\txwa, (SCRATCH)")
        A("\tret")
    A("")
    A(";===============================================================")
    A("; clean-room font, pre-expanded to 2bpp CHAR-RAM tiles (256 x 16 B)")
    A(";===============================================================")
    A("_font_data:")
    font = build_font_2bpp()
    for off in range(0, len(font), 16):
        row = ", ".join(f"0x{b:02x}" for b in font[off:off + 16])
        A(f"\tdb\t{row}")
    A("")
    A(";===============================================================")
    A("; BIOS system-call table @ 0xFFFE00 (indexed by RW3)")
    A(";===============================================================")
    A("SYSCALL_TBL\tsection code large align=1,1")
    sc_stub = SC_STUB
    for i in range(SYSCALL_SLOTS):
        lbl = sc_stub.get(i, "_sc_ret")
        A(f"\tdl\t{lbl:<10s}       ; {i:#04x}")
    A("")
    A(";===============================================================")
    A("; CPU hardware vector table @ 0xFFFF00 (index*4)")
    A(";===============================================================")
    A("INT_VECTOR\tsection code large align=1,1")
    for i in range(HW_TABLE_SLOTS):
        if i == 0:
            tgt, note = "_boot", "reset / swi0"
        elif i == 1:
            tgt, note = "_swi1", "swi 1 (system call)"
        elif i in SERIAL_ISR:
            tgt, note = SERIAL_ISR[i], "link cable -- the BIOS owns this one"
        elif i in chain_label:
            tgt, note = chain_label[i], f"-> user slot {USER_SLOT[i]:#06x}"
        else:
            tgt, note = "_reti", "unused"
        A(f"\tdl\t{tgt:<12s}       ; {i:#04x} {note}")
    A("")
    A("\tend")
    return "\r\n".join(out) + "\r\n"


if __name__ == "__main__":
    import sys
    if "--regen-font" in sys.argv:
        data = rasterise_font_2bpp()
        with open(FONT_BIN, "wb") as f:
            f.write(data)
        print("wrote", FONT_BIN)
        raise SystemExit(0)
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "src", "crt0.asm")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="") as f:
        f.write(gen())
    print("wrote", path)
