"""TMP95C061 8-bit timers 0..3.

Expectations come from the Toshiba datasheet + the official SNK SDK
(`01_SDK/docs/8Bit.txt`) -- see core/timers.py.
"""

from __future__ import annotations

import unittest

from core.frame_timing import CYCLES_PER_SCANLINE
from core.timers import (
    CYCLES_T1,
    CYCLES_T4,
    CYCLES_T16,
    CYCLES_T256,
    IRQ_VECTOR_INDEX_INTT0,
    IRQ_VECTOR_INDEX_INTT1,
    IRQ_VECTOR_INDEX_INTT2,
    IRQ_VECTOR_INDEX_INTT3,
    T01MOD_ADDRESS,
    TREG0_ADDRESS,
    TREG1_ADDRESS,
    TRUN_ADDRESS,
    TRUN_PRESCALER,
    TimerController,
)


class TimerVectorTests(unittest.TestCase):
    def test_intt_vectors_match_the_toshiba_table(self) -> None:
        # Table 3.3 (1): INTT0 = 0x0040, INTT1 = 0x0044, INTT2 = 0x0048,
        # INTT3 = 0x004C -> hardware vector index = vector value / 4.
        self.assertEqual(IRQ_VECTOR_INDEX_INTT0, 16)
        self.assertEqual(IRQ_VECTOR_INDEX_INTT1, 17)
        self.assertEqual(IRQ_VECTOR_INDEX_INTT2, 18)
        self.assertEqual(IRQ_VECTOR_INDEX_INTT3, 19)

    def test_prescaler_taps_are_self_consistent(self) -> None:
        # SDK 8Bit.txt periods at 6.144 MHz: T1=128, T4=512, T16=2048, T256=32768.
        self.assertEqual(CYCLES_T4, CYCLES_T1 * 4)
        self.assertEqual(CYCLES_T16, CYCLES_T1 * 16)
        self.assertEqual(CYCLES_T256, CYCLES_T1 * 256)


class TimerCountingTests(unittest.TestCase):
    def test_stopped_prescaler_produces_nothing(self) -> None:
        # SDK: <PRRUN> = 0 zero-clears and STOPS the prescaler.
        timers = TimerController()
        # Prescaler bit clear -> the internal taps produce nothing.
        memory = {TRUN_ADDRESS: 0x01, TREG0_ADDRESS: 1, T01MOD_ADDRESS: 0x01}
        self.assertEqual(timers.tick(100000, memory), [])

    def test_stopped_timer_produces_nothing(self) -> None:
        timers = TimerController()
        memory = {
            TRUN_ADDRESS: TRUN_PRESCALER,  # prescaler on, timer 0 off
            TREG0_ADDRESS: 1,
            T01MOD_ADDRESS: 0x01,
        }
        self.assertEqual(timers.tick(100000, memory), [])

    def test_timer0_on_t1_fires_intt0_at_the_compare_value(self) -> None:
        # T01MOD bits 1-0 = 01 -> timer 0 clocked by T1 (128 CPU cycles).
        # TREG0 = 3 -> the comparator matches after 3 T1 ticks.
        timers = TimerController()
        memory = {
            TRUN_ADDRESS: TRUN_PRESCALER | 0x01,
            TREG0_ADDRESS: 3,
            T01MOD_ADDRESS: 0x01,
        }
        self.assertEqual(timers.tick(CYCLES_T1 * 2, memory), [])  # 2 ticks: no match
        self.assertEqual(
            timers.tick(CYCLES_T1, memory), [IRQ_VECTOR_INDEX_INTT0]
        )  # 3rd tick
        # Counter zero-cleared on match, so the next match is another 3 ticks out.
        self.assertEqual(timers.tick(CYCLES_T1 * 2, memory), [])
        self.assertEqual(timers.tick(CYCLES_T1, memory), [IRQ_VECTOR_INDEX_INTT0])

    def test_timer0_t4_is_four_times_slower_than_t1(self) -> None:
        timers = TimerController()
        memory = {
            TRUN_ADDRESS: TRUN_PRESCALER | 0x01,
            TREG0_ADDRESS: 1,
            T01MOD_ADDRESS: 0x02,  # source 10 = T4
        }
        self.assertEqual(timers.tick(CYCLES_T4 - 1, memory), [])
        self.assertEqual(timers.tick(1, memory), [IRQ_VECTOR_INDEX_INTT0])

    def test_treg_zero_matches_on_overflow(self) -> None:
        # SDK: "if the value is set to 00H, unison check becomes active when the
        # up counter is in overflow status" -> 256 ticks, not 0.
        timers = TimerController()
        memory = {
            TRUN_ADDRESS: TRUN_PRESCALER | 0x01,
            TREG0_ADDRESS: 0,
            T01MOD_ADDRESS: 0x01,
        }
        self.assertEqual(timers.tick(CYCLES_T1 * 255, memory), [])
        self.assertEqual(timers.tick(CYCLES_T1, memory), [IRQ_VECTOR_INDEX_INTT0])

    def test_timer0_external_clock_counts_the_rasters_pulses_not_cycles(self) -> None:
        # SDK 8Bit.txt: "In the NEOGEO POCKET, the horizontal blanking interrupt
        # generated by the 2D graphic controller is the external clock TI0."
        # The pulses come FROM THE VIDEO CLOCK (RasterController.take_hint_pulses),
        # on the spec's own schedule. Deriving them in here from a private cycle
        # count is exactly the defect that made Metal Slug's raster split flicker
        # one line up and down: same arithmetic, WRONG CLOCK (DEVLOG 2026-07-16).
        timers = TimerController()
        memory = {
            TRUN_ADDRESS: TRUN_PRESCALER | 0x01,
            TREG0_ADDRESS: 2,
            T01MOD_ADDRESS: 0x00,
        }
        # Cycles alone -- a whole frame of them -- carry NO TI0 pulse.
        self.assertEqual(timers.tick(CYCLES_PER_SCANLINE * 199, memory), [])
        # The raster's pulses are what count.
        self.assertEqual(timers.tick(0, memory, hint_pulses=1), [])
        self.assertEqual(
            timers.tick(0, memory, hint_pulses=1), [IRQ_VECTOR_INDEX_INTT0]
        )

    def test_the_raster_pulses_the_spec_schedule(self) -> None:
        # ngpcspec.txt: "The signal generation begins 1 H before the Hardware
        # Drawing Period starts. (Please be aware H_INT signal is not generated
        # at line 151 and signal generation for the 0th line occurs at the
        # beginning of line 198.)" => a pulse entering lines 198 and 0..150,
        # and "152 Hint occur every time" (K2GETechRef 4-5-2).
        from core.frame_timing import (
            SCANLINES_PER_FRAME,
            VISIBLE_SCANLINES,
            RasterController,
        )

        raster = RasterController()  # starts at line 0
        pulses_at: dict[int, int] = {}
        for _ in range(SCANLINES_PER_FRAME):
            raster.tick(CYCLES_PER_SCANLINE)  # cross into the next line
            pulses_at[raster.frame_state.scanline] = raster.take_hint_pulses()
        for line, got in sorted(pulses_at.items()):
            want = 1 if (line == SCANLINES_PER_FRAME - 1 or line <= VISIBLE_SCANLINES - 2) else 0
            self.assertEqual(
                got, want, f"entering line {line}: expected {want} pulse(s), got {got}"
            )
        self.assertEqual(sum(pulses_at.values()), 152, "152 Hint occur every time")

    def test_timer1_cascades_from_timer0_overflow(self) -> None:
        # T01MOD bits 3-2 = 00 -> timer 1 is clocked by timer 0's overflow
        # (16-bit cascade). Timer 0 on T1 with TREG0=1 overflows every tick.
        timers = TimerController()
        memory = {
            TRUN_ADDRESS: TRUN_PRESCALER | 0x03,  # both timers running
            TREG0_ADDRESS: 1,
            TREG1_ADDRESS: 2,
            T01MOD_ADDRESS: 0x01,  # T0 = T1 clock, T1 = cascade (bits 3-2 = 00)
        }
        # First timer-0 match: INTT0 only (timer 1 has counted 1 of 2).
        self.assertEqual(timers.tick(CYCLES_T1, memory), [IRQ_VECTOR_INDEX_INTT0])
        # Second: timer 0 matches again AND timer 1 reaches its compare value.
        self.assertEqual(
            timers.tick(CYCLES_T1, memory),
            [IRQ_VECTOR_INDEX_INTT0, IRQ_VECTOR_INDEX_INTT1],
        )

    def test_timer1_on_its_own_prescaler_tap_ignores_the_cascade(self) -> None:
        # T01MOD bits 3-2 = 01 -> timer 1 clocked by T1 directly.
        timers = TimerController()
        memory = {
            TRUN_ADDRESS: TRUN_PRESCALER | 0x02,  # only timer 1 running
            TREG1_ADDRESS: 1,
            T01MOD_ADDRESS: 0x04,
        }
        self.assertEqual(timers.tick(CYCLES_T1, memory), [IRQ_VECTOR_INDEX_INTT1])

    def test_timer2_has_no_external_clock_pin(self) -> None:
        # SDK: "timer 0 has an external clock TI0 terminal. Timer 2 does not."
        # So source 00 on timer 2 counts nothing -- not even the raster's pulses.
        timers = TimerController()
        memory = {
            TRUN_ADDRESS: TRUN_PRESCALER | 0x04,
            0x000026: 1,  # TREG2
            0x000028: 0x00,  # T23MOD: timer 2 source 00
        }
        self.assertEqual(timers.tick(CYCLES_PER_SCANLINE * 10, memory, hint_pulses=10), [])

    def test_timer3_fires_its_own_vector(self) -> None:
        timers = TimerController()
        memory = {
            TRUN_ADDRESS: TRUN_PRESCALER | 0x08,
            0x000027: 1,  # TREG3
            0x000028: 0x04,  # T23MOD bits 3-2 = 01 -> timer 3 on T1
        }
        self.assertEqual(timers.tick(CYCLES_T1, memory), [IRQ_VECTOR_INDEX_INTT3])

    def test_timer2_on_prescaler_fires_intt2(self) -> None:
        timers = TimerController()
        memory = {
            TRUN_ADDRESS: TRUN_PRESCALER | 0x04,
            0x000026: 1,  # TREG2
            0x000028: 0x01,  # T23MOD bits 1-0 = 01 -> timer 2 on T1
        }
        self.assertEqual(timers.tick(CYCLES_T1, memory), [IRQ_VECTOR_INDEX_INTT2])


if __name__ == "__main__":
    unittest.main()
