"""TMP95C061 8-bit timers 0..3.

Transcribed from the Toshiba TMP95C061 datasheet and the official SNK SDK
(`01_SDK/docs/8Bit.txt`). Nothing here is guessed.

Registers (SDK 8Bit.txt + datasheet):
    TRUN   (0x0020)  bit n = run timer n; bit 7 = PRRUN (prescaler run)
    TREG0  (0x0022)  timer 0 compare value   (write-only on hardware)
    TREG1  (0x0023)  timer 1 compare value
    T01MOD (0x0024)  bits 1-0 = timer 0 clock source
                     bits 3-2 = timer 1 clock source
    TREG2  (0x0026)  timer 2 compare value
    TREG3  (0x0027)  timer 3 compare value
    T23MOD (0x0028)  bits 1-0 = timer 2 clock source
                     bits 3-2 = timer 3 clock source

Clock sources (SDK 8Bit.txt "the parameter set in T01MOD determines the input"):
    timer 0 / timer 2 : 00 = external TI0, 01 = T1, 10 = T4, 11 = T16
    timer 1 / timer 3 : 00 = overflow of the paired timer (16-bit cascade),
                        01 = T1, 10 = T16, 11 = T256
    On the NGPC "the horizontal blanking interrupt generated by the 2D graphic
    controller is the external clock TI0" (SDK 8Bit.txt) -- so source 00 on
    timer 0 counts scanlines. Timer 2 has no external clock pin.

Prescaler periods (SDK 8Bit.txt, measured values): T1 = 20.83 us, T4 = 83.33 us,
T16 = 333.3 us, T256 = 5.333 ms. At the NGPC's 6.144 MHz CPU clock that is
T1 = 128 CPU cycles, T4 = 512, T16 = 2048, T256 = 32768 -- self-consistent
(128 * 256 = 32768).

  NOTE: the reference emulator uses TIMER_BASE_RATE = 240 rather than 128 (its
  timer path even carries "HACK" comments). We follow the SDK, which states
  measured periods, over a hand-tuned constant.

Comparator (SDK 8Bit.txt 4): "If it is in unison (the same), the up counter is
0 cleared and an interrupt (INTT0~3) is generated." A TREG of 0 matches on
counter overflow.

Interrupt vectors (Toshiba Table 3.3 (1)): INTT0 = 0x0040, INTT1 = 0x0044,
INTT2 = 0x0048, INTT3 = 0x004C -> hardware vector indices 16..19.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from core.memory import io_reset_value
from core.frame_timing import (
    CYCLES_PER_SCANLINE,
    SCANLINES_PER_FRAME,
    VISIBLE_SCANLINES,
)

TRUN_ADDRESS = 0x000020
TREG0_ADDRESS = 0x000022
TREG1_ADDRESS = 0x000023
T01MOD_ADDRESS = 0x000024
TREG2_ADDRESS = 0x000026
TREG3_ADDRESS = 0x000027
T23MOD_ADDRESS = 0x000028

TRUN_PRESCALER = 0x80

# Prescaler taps, in CPU cycles.
#
# ⚖️ MEASURED ON SILICON. T1 = 128. An EAR had put it at 512 -- wrongly.
#
# The whole ladder hangs off T1, and the music tempo of every NGPC game hangs off
# the ladder: timer 3 is the only interrupt that drives the sound CPU, and the games
# all program it identically (T23MOD = 0x05, TREG3 = 98).
#
#   hw_calibration/bin/main.ngc -- official Toshiba toolchain, flashed on a real
#   NGPC -- counts INTT3 across 120 VBlanks and PRINTS the count. The console
#   printed 03D0 = 976, i.e. ~488 ticks a second:
#
#       1 / (488 x 98) s  =  20.9 us  =  128 cycles at 6.144 MHz     ->  T1 = 128
#
# ⛔ THE HISTORY, BECAUSE IT IS THE LESSON. This core used 128. A playtest said the
# music ran "far too fast", so it was moved to 512 -- picked by ear, blind, from four
# candidates, and the corpus even seemed to agree. It was wrong. The audio pipeline
# was ALSO broken at the time (the player free-ran at 62.5 fps and piled up one to
# two seconds of latency), so the tempo was being judged THROUGH a defect.
#
# ⇒ Do not re-tune this by listening. The ROM prints an integer; the ear does not.
CYCLES_T1 = 128
CYCLES_T4 = 512
CYCLES_T16 = 2048
CYCLES_T256 = 32768

# Toshiba Table 3.3 (1): vector value / 4.
IRQ_VECTOR_INDEX_INTT0 = 0x0040 // 4  # 16
IRQ_VECTOR_INDEX_INTT1 = 0x0044 // 4  # 17
IRQ_VECTOR_INDEX_INTT2 = 0x0048 // 4  # 18
IRQ_VECTOR_INDEX_INTT3 = 0x004C // 4  # 19

# Clock-source tables, indexed by the 2-bit mode field.
# `None` = "not an internal prescaler tap" (external pin, or cascade).
_EVEN_TIMER_SOURCES = (None, CYCLES_T1, CYCLES_T4, CYCLES_T16)
_ODD_TIMER_SOURCES = (None, CYCLES_T1, CYCLES_T16, CYCLES_T256)


@dataclass
class TimerController:
    """The four 8-bit up-counters. Owned by `EmulatorSession` so counters
    survive across step batches; ticked with the cycles each instruction cost.

    Counters are internal chip state (the up-counters are not memory-mapped), so
    they live here rather than in the I/O overlay. TREG/TRUN/TxxMOD are read
    from the overlay, which is where software's writes land.
    """

    counters: list[int] = field(default_factory=lambda: [0, 0, 0, 0])
    _clock: list[int] = field(default_factory=lambda: [0, 0, 0, 0])

    def reset(self) -> None:
        self.counters = [0, 0, 0, 0]
        self._clock = [0, 0, 0, 0]

    def tick(self, cycles: int, memory: dict[int, int],
             hint_pulses: int = 0) -> list[int]:
        """Advance the timers by `cycles` CPU clocks.

        `hint_pulses` is how many H-INT pulses the VIDEO CLOCK produced during
        those cycles -- the K2GE's TI0 pin, which timer 0 counts in mode 00. The
        pulses come from `RasterController.take_hint_pulses()`, i.e. from the
        raster's OWN clock, on the spec's own schedule (the start of lines 198
        and 0..150 -- "the signal generation begins 1 H before the Hardware
        Drawing Period starts", ngpcspec.txt; 152 per frame, K2GETechRef 4-5-2).

        They used to be derived HERE, from a private cycle accumulator. Same
        arithmetic, wrong clock: its phase against the raster was arbitrary and
        drifted 13 cycles per IRQ delivery, and Metal Slug's raster split
        flickered across a line boundary with it (DEVLOG 2026-07-16). Both
        cores now take the pulses from their raster.

        Returns the hardware vector indices of any INTT0..3 that fired.
        """
        if cycles <= 0 and hint_pulses <= 0:
            return []
        trun = memory.get(TRUN_ADDRESS, io_reset_value(TRUN_ADDRESS)) & 0xFF
        if not (trun & TRUN_PRESCALER):
            # PRRUN = 0: the prescaler is cleared and stopped, so the internal
            # taps produce nothing. (SDK: <PRRUN>=0 zero-clears and stops it.)
            # The TI0 pulses are DISCARDED, not banked -- the pin pulses whether
            # or not anyone is listening, exactly as this behaved before.
            return []
        hblanks = hint_pulses

        t01mod = memory.get(T01MOD_ADDRESS, io_reset_value(T01MOD_ADDRESS)) & 0xFF
        t23mod = memory.get(T23MOD_ADDRESS, io_reset_value(T23MOD_ADDRESS)) & 0xFF
        modes = (t01mod & 0x03, (t01mod >> 2) & 0x03, t23mod & 0x03, (t23mod >> 2) & 0x03)
        tregs = (
            memory.get(TREG0_ADDRESS, io_reset_value(TREG0_ADDRESS)) & 0xFF,
            memory.get(TREG1_ADDRESS, io_reset_value(TREG1_ADDRESS)) & 0xFF,
            memory.get(TREG2_ADDRESS, io_reset_value(TREG2_ADDRESS)) & 0xFF,
            memory.get(TREG3_ADDRESS, io_reset_value(TREG3_ADDRESS)) & 0xFF,
        )
        vectors = (
            IRQ_VECTOR_INDEX_INTT0,
            IRQ_VECTOR_INDEX_INTT1,
            IRQ_VECTOR_INDEX_INTT2,
            IRQ_VECTOR_INDEX_INTT3,
        )

        raised: list[int] = []
        # Cascade inputs: an odd timer in mode 00 counts the paired timer's
        # overflows (16-bit timer mode).
        cascade = [0, 0, 0, 0]

        for index in (0, 1, 2, 3):
            if not (trun & (1 << index)):
                continue
            mode = modes[index]
            even = index % 2 == 0

            if even:
                period = _EVEN_TIMER_SOURCES[mode]
                # Mode 00 on timer 0 = external TI0 = the horizontal blank.
                # Timer 2 has no external clock pin, so it simply does not count.
                ticks = hblanks if (period is None and index == 0) else 0
            else:
                period = _ODD_TIMER_SOURCES[mode]
                ticks = cascade[index - 1] if period is None else 0

            if period is not None:
                self._clock[index] += cycles
                ticks, self._clock[index] = divmod(self._clock[index], period)

            if ticks <= 0:
                continue

            treg = tregs[index]
            # A TREG of 0 matches on overflow (SDK: "if the value is set to 00H,
            # unison check becomes active when the up counter is in overflow").
            limit = treg if treg else 0x100
            total = self.counters[index] + ticks
            matches, self.counters[index] = divmod(total, limit)
            if matches:
                if even:
                    cascade[index] = matches
                raised.append(vectors[index])

        return raised
